const app = document.getElementById('app');
const state = { user:null, services:[], view:'home' };
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api = async (url, opts={}) => { const r=await fetch(url,opts); let j={}; try{j=await r.json()}catch{} if(!r.ok) throw Object.assign(new Error(j.message||'Request failed'),{status:r.status,data:j}); return j; };

function brandMarkup(sub='Citizen Digital Platform'){
  return `<div class="brand"><div class="brand-mark">KS</div><div><strong>Koutilya Solutions</strong><small>${esc(sub)}</small></div></div>`;
}
function showMsg(id,text,type='err'){const el=document.getElementById(id); if(!el)return; el.className='msg '+type; el.textContent=text;}

function auth(){
  app.innerHTML=`<main class="auth-page"><div class="auth-split"><section class="auth-showcase">
    <div class="showcase-brand">${brandMarkup('Citizen Digital Platform')}</div>
    <div class="showcase-copy"><span class="eyebrow">KOUTILYA SOLUTIONS PRIVATE LIMITED</span><h1>Digital Citizen Services, made simple.</h1><p>Prepare citizen applications and affidavits online, keep documents ready, manage your wallet and track your service transactions from one secure portal.</p></div>
    <div class="showcase-grid">
      <div><b>▣</b><strong>MeeSeva Applications</strong><span>Digital application preparation</span></div>
      <div><b>▤</b><strong>Affidavits & Declarations</strong><span>Service-specific document drafts</span></div>
      <div><b>◈</b><strong>Digital Documents</strong><span>Generate and save your PDF</span></div>
      <div><b>₹</b><strong>Secure Wallet</strong><span>Top-up and pay service fees</span></div>
      <div><b>↕</b><strong>Transactions</strong><span>View your payment history</span></div>
      <div><b>?</b><strong>Citizen Support</strong><span>Get help and raise complaints</span></div>
    </div>
    <div class="showcase-footer"><span>INNOVATE • DEVELOP • DELIVER</span><span>Secure • Convenient • Digital</span></div>
  </section><section class="auth-side"><div class="auth-card">
    ${brandMarkup('Secure Portal Login')}<h2>Welcome back</h2><p class="auth-lead">Sign in with your Koutilya User ID or authorized Admin ID to continue.</p>
    <form id="loginForm"><div class="field"><label for="uid">User ID</label><input id="uid" autocomplete="username" placeholder="Enter User ID" required></div><div class="field"><label for="pw">Password</label><input id="pw" type="password" autocomplete="current-password" placeholder="Enter password" required><label style="display:flex;align-items:center;gap:7px;margin-top:8px;font-weight:600;font-size:12px;color:#526579;cursor:pointer"><input id="showPw" type="checkbox" style="width:auto;margin:0"> Show password</label></div><button class="primary" type="submit">Login</button></form>
    <div id="msg" class="msg hidden"></div><div class="auth-divider"><span>New citizen?</span></div><button class="outline-btn" id="registerBtn" type="button">Create New Citizen Account</button>
  </div><div class="auth-note">Your account gives you access to citizen services available on this portal. Requirements and acceptance remain subject to the concerned authority.</div></section></div></main>`;
  document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();loginUser();});
  document.getElementById('showPw').addEventListener('change',e=>{document.getElementById('pw').type=e.target.checked?'text':'password';});
  document.getElementById('registerBtn').addEventListener('click',register);
}

function register(){
  app.innerHTML=`<main class="auth-page"><div class="auth-split"><section class="auth-showcase compact">${brandMarkup('Citizen Registration')}<div class="showcase-copy"><span class="eyebrow">NEW CITIZEN ACCOUNT</span><h1>Start your digital service journey.</h1><p>Register once and use the same Koutilya User ID for applications, affidavits, wallet, transactions and support.</p></div><div class="registration-points"><div>✓ Unique Koutilya User ID</div><div>✓ Temporary password for first login</div><div>✓ Mandatory password change for security</div><div>✓ Citizen profile linked to your account</div></div></section><section class="auth-side"><div class="auth-card">
    ${brandMarkup('Citizen Registration')}<h2>Create your account</h2><p class="auth-lead">Enter the details below. Your unique User ID and temporary password will be sent to your registered email address.</p>
    <form id="regForm"><div class="form-grid"><div class="field"><label for="regName">Full Name</label><input id="regName" autocomplete="name" required></div><div class="field"><label for="regMobile">Mobile Number</label><input id="regMobile" inputmode="numeric" maxlength="10" autocomplete="tel" required></div><div class="field"><label for="regEmail">Email ID</label><input id="regEmail" type="email" autocomplete="email" required></div><div class="field"><label for="regCity">City</label><input id="regCity" autocomplete="address-level2" required></div></div><button class="primary" type="submit">Register Citizen Account</button></form>
    <div id="regMsg" class="msg hidden"></div><div class="auth-links"><button class="link-btn" id="backLogin" type="button">← Back to Login</button></div>
  </div></section></div></main>`;
  document.getElementById('regForm').addEventListener('submit',async e=>{e.preventDefault(); const btn=e.submitter;btn.disabled=true;showMsg('regMsg','Creating your citizen account and sending credentials to your email…','info');try{const j=await api('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:document.getElementById('regName').value.trim(),mobile:document.getElementById('regMobile').value.trim(),email:document.getElementById('regEmail').value.trim(),city:document.getElementById('regCity').value.trim()})});showMsg('regMsg',j.message,'ok');setTimeout(auth,4500);}catch(err){showMsg('regMsg',err.message,'err')}finally{btn.disabled=false;}});
  document.getElementById('backLogin').addEventListener('click',auth);
}

async function loginUser(){
  const btn=document.querySelector('#loginForm .primary');btn.disabled=true;showMsg('msg','Signing in…','info');
  try{const j=await api('/api/auth/unified-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:document.getElementById('uid').value.trim(),password:document.getElementById('pw').value})});
    if(j.authToken)localStorage.setItem('kspl_auth_token',j.authToken);
    if(j.role==='admin'){location.href=j.redirect||'/admin/dashboard';return;}
    state.user=j.user;if(j.user.mustChangePassword){forceChange();return;}await boot();
  }catch(e){showMsg('msg',e.message,'err');}finally{if(btn)btn.disabled=false;}
}
function forceChange(){
  app.innerHTML=`<main class="auth-page"><div class="auth-card narrow">${brandMarkup('First Login Security')}<h2>Change your temporary password</h2><p class="auth-lead">For your security, the temporary password must be changed before you can use the portal.</p><form id="changeForm"><div class="field"><label>Current Password</label><input id="cur" type="password" required><label class="show-password"><input id="showCur" type="checkbox"> Show password</label></div><div class="field"><label>New Password</label><input id="newp" type="password" minlength="8" required placeholder="Minimum 8 characters"><label class="show-password"><input id="showNew" type="checkbox"> Show password</label></div><div class="field"><label>Confirm New Password</label><input id="conf" type="password" minlength="8" required><label class="show-password"><input id="showConf" type="checkbox"> Show password</label></div><button class="primary" type="submit">Change Password</button></form><div id="changeMsg" class="msg hidden"></div></div></main>`;
  document.getElementById('showCur').addEventListener('change',e=>cur.type=e.target.checked?'text':'password');document.getElementById('showNew').addEventListener('change',e=>newp.type=e.target.checked?'text':'password');document.getElementById('showConf').addEventListener('change',e=>conf.type=e.target.checked?'text':'password');document.getElementById('changeForm').addEventListener('submit',async e=>{e.preventDefault();try{const j=await api('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:cur.value,newPassword:newp.value,confirmPassword:conf.value})});showMsg('changeMsg',j.message,'ok');localStorage.removeItem('kspl_auth_token');setTimeout(auth,1800);}catch(err){showMsg('changeMsg',err.message,'err');}});
}

function shell(){
 app.innerHTML=`<div class="portal"><header class="topbar"><div class="top-brand"><div class="brand-mark small">KS</div><div><span>Koutilya Solutions</span><small>Citizen Digital Platform</small></div></div><div class="top-spacer"></div><div class="top-user"><div class="avatar" id="avatar">K</div><div><strong id="topname"></strong><small id="topid"></small></div></div></header><div class="layout"><aside class="sidebar"><div class="side-title">CITIZEN MENU</div>${[
 ['home','⌂','Home'],['services','▣','MeeSeva Applications'],['affidavits','▤','Affidavits'],['pvc','◈','Print PVC'],['wallet','₹','Wallet'],['transactions','↕','Transactions'],['complaint','?','Raise a Complaint'],['profile','●','Profile'],['password','🔒','Change Password'],['logout','↪','Logout']].map(x=>`<button class="navbtn" data-view="${x[0]}"><span class="navicon">${x[1]}</span><span>${x[2]}</span></button>`).join('')}</aside><main class="content" id="content"></main></div><footer class="bottom">Koutilya Digital Platform</footer><button class="chat-toggle" id="chatToggle">?</button><div id="chatRoot"></div></div>`;
 document.querySelectorAll('.navbtn').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));document.getElementById('chatToggle').addEventListener('click',toggleChat);updateUser();
}
function updateUser(){document.getElementById('topname').textContent=state.user.name;document.getElementById('topid').textContent=state.user.userId;document.getElementById('avatar').textContent=(state.user.name||'K')[0].toUpperCase();}
async function boot(){shell();await loadServices();await handleReturn();navigate('home');}
async function loadServices(){try{const j=await api('/api/affidavits');state.services=j.services||[];}catch(e){state.services=[];}}
function navigate(v){state.view=v;document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const fn={home,services,affidavits,pvc,wallet,transactions,complaint,profile,password,logout}[v]||home;fn();}

async function home(){content.innerHTML=`<section class="hero"><div><span class="eyebrow">KOUTILYA SOLUTIONS</span><h1>Welcome, ${esc(state.user.name)}</h1><p>Your citizen services are available from one secure digital workspace.</p></div><div class="hero-id"><small>USER ID</small><strong>${esc(state.user.userId)}</strong></div></section><div class="cards" id="stats"><div class="stat"><span>Completed Transactions</span><strong>—</strong></div><div class="stat"><span>Amount Spent</span><strong>—</strong></div><div class="stat"><span>Wallet Balance</span><strong>—</strong></div></div><section class="panel"><div class="panel-head"><div><h2>Quick Services</h2><p>Choose a service and continue without leaving your dashboard.</p></div></div><div class="service-grid quick"><div class="service" data-go="services"><div class="ico blue">▣</div><strong>MeeSeva Applications</strong><span>Late registration, income, EWS, OBC, caste, family and seeding applications.</span></div><div class="service" data-go="affidavits"><div class="ico purple">▤</div><strong>Affidavits & Declarations</strong><span>Browse 80 citizen-use affidavit and declaration services.</span></div><div class="service" data-go="wallet"><div class="ico green">₹</div><strong>Wallet</strong><span>Add balance securely and use it for service fees.</span></div><div class="service" data-go="transactions"><div class="ico orange">↕</div><strong>Transactions</strong><span>Search your service and wallet transaction history.</span></div></div></section><section class="panel note-panel"><div class="note-icon">✓</div><div><h3>How Koutilya helps</h3><p>We provide digital preparation of citizen-service applications and citizen-use affidavits, PDF generation, wallet-based service payments, transaction records and support. The concerned authority remains responsible for statutory approval, verification and final acceptance.</p></div></section>`;
 document.querySelectorAll('[data-go]').forEach(x=>x.addEventListener('click',()=>navigate(x.dataset.go)));try{const j=await api('/api/portal/dashboard');stats.innerHTML=`<div class="stat"><span>Completed Transactions</span><strong>${j.stats.transactions}</strong></div><div class="stat"><span>Amount Spent</span><strong>₹${j.stats.amountSpent.toFixed(2)}</strong></div><div class="stat"><span>Wallet Balance</span><strong>₹${j.stats.balance.toFixed(2)}</strong></div>`;}catch(e){}
}
const meeseva=[['death','Late Registration of Death','/forms/death.html'],['late-birth','Late Registration of Birth','/forms/late-birth.html'],['income','Income Certificate','/forms/income.html'],['ews','EWS Income Certificate','/forms/ews.html'],['obc','OBC Certificate','/forms/obc.html'],['caste-integrated','Caste / Integrated Certificate','/forms/caste-integrated.html'],['family-member','Family Membership Certificate','/forms/family-member.html'],['seeding','Pattadar Aadhaar Seeding','/forms/seeding.html']];
const meesevaChecklists={death:['Applicant Aadhaar / valid ID proof','Deceased person death record / hospital or burial evidence, as applicable','Address / residence proof','Relationship proof, if required','Passport-size photograph, if requested'], 'late-birth':['Applicant/parent Aadhaar or valid ID','Proof of birth such as hospital/birth record, if available','Address / residence proof','Parent/guardian relationship proof','Documents explaining delayed registration, if required'],income:['Applicant identity proof','Address/residence proof','Income/source supporting documents','Family/income particulars','Authority-specific application or certificate records, if required'],ews:['Identity and address proof','Family income/source records','Asset/property particulars','Agricultural land/property records where applicable','EWS application/supporting documents required by the authority'],obc:['Identity and address proof','Community/caste supporting record','Family/income details','Non-creamy-layer supporting records where applicable','Authority-specific OBC/NCL documents'], 'caste-integrated':['Identity and address proof','Caste/community supporting record','Previous caste certificate, if any','Family/parent community records where applicable','Authority-specific integrated certificate documents'], 'family-member':['Applicant identity/address proof','Death certificate or reference record, where applicable','Relationship/family records','Family member identity records','Authority-specific family membership documents'],seeding:['Pattadar/passbook or land record','Aadhaar/identity details','Survey and land particulars','Mobile number linked/required for service','Authority-specific seeding records']};
function serviceIcon(key){return ({death:'⚱', 'late-birth':'♣',income:'₹',ews:'✓',obc:'◉','caste-integrated':'◈','family-member':'♧',seeding:'⌁'})[key]||'▣';}
function services(){content.innerHTML=`<section class="panel"><div class="panel-head"><div><span class="eyebrow">CITIZEN SERVICES</span><h2>MeeSeva Applications</h2><p>Select an application to complete the existing working form inside the secure portal.</p></div><div class="fee-badge">Service fee <b>₹2</b></div></div><div class="service-grid">${meeseva.map(([k,t])=>`<div class="service" data-service="${k}"><div class="ico blue">${serviceIcon(k)}</div><strong>${esc(t)}</strong><span>Open application form</span><em>₹2 on PDF generation</em></div>`).join('')}</div></section>`;document.querySelectorAll('[data-service]').forEach(x=>x.addEventListener('click',()=>{const row=meeseva.find(y=>y[0]===x.dataset.service);openFormWorkspace(row[2],row[0],row[1],2,meesevaChecklists[row[0]]||[],'meeseva');}));}
function affidavits(){const cats=[...new Set(state.services.map(x=>x.category).filter(Boolean))].sort();const depts=[...new Set(state.services.flatMap(x=>x.departments||[]).filter(Boolean))].sort();const states=['Andhra Pradesh','Telangana','Other States / Authorities'];content.innerHTML=`<section class="panel"><div class="panel-head"><div><span class="eyebrow">AFFIDAVITS & DECLARATIONS</span><h2>Prepare the documents for your case</h2><p>Select the authority area and service. Koutilya uses the service and your case facts to determine the applicable document package.</p></div><div class="fee-badge">Service fee <b>₹5</b></div></div><div class="toolbar"><input id="affSearch" placeholder="Search service or purpose…"><select id="affDept"><option value="">All departments</option>${depts.map(c=>`<option>${esc(c)}</option>`).join('')}</select><select id="affState"><option value="">All states / authorities</option>${states.map(c=>`<option>${esc(c)}</option>`).join('')}</select><select id="affCat"><option value="">All categories</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div class="aff-guidance"><b>You do not need to decide which affidavit or declaration is required.</b> Choose the service that describes your case and provide the facts requested. The final checklist and document package are determined by the service rules. Authority-prescribed formats are used only when verified.</div><div id="affGrid" class="service-grid affidavit-grid"></div></section>`;const render=()=>{const q=affSearch.value.toLowerCase(),c=affCat.value,d=affDept.value,st=affState.value;const rows=state.services.filter(x=>(!q||((x.title||'')+' '+(x.category||'')+' '+(x.purpose||'')).toLowerCase().includes(q))&&(!c||x.category===c)&&(!d||(x.departments||[]).includes(d))&&(!st||(x.jurisdictions||[]).some(j=>j===st||j.includes(st))));affGrid.innerHTML=rows.map(x=>`<div class="service" data-aff="${esc(x.id)}"><div class="ico purple">▤</div><strong>${esc(x.title)}</strong><span>${esc((x.departments||[]).join(' · '))}<br>${esc(x.purpose||'Case-specific document preparation')}</span><em>₹5 on PDF generation</em></div>`).join('')||'<div class="empty-state">No matching document services found.</div>';affGrid.querySelectorAll('[data-aff]').forEach(x=>x.addEventListener('click',()=>openAff(x.dataset.aff)));};affSearch.addEventListener('input',render);affCat.addEventListener('change',render);affDept.addEventListener('change',render);affState.addEventListener('change',render);render();}
function openAff(id){const item=state.services.find(x=>x.id===id);let url='/forms/universal-affidavit.html?id='+encodeURIComponent(id);if(id==='late-death-registration')url='/forms/death-affidavit.html';if(id==='family-member')url='/forms/family-member-affidavit.html';if(id==='one-same-person')url='/forms/one-same-person-affidavit.html';if(id==='name-difference')url='/forms/name-difference-affidavit.html';openFormWorkspace(url,id,item?.title||'Affidavit / Declaration',5,item?.checklist||[], 'affidavit');}
function openFormWorkspace(url,key,title,fee,checklistItems,type){content.innerHTML=`<section class="panel form-panel"><div class="panel-head"><div><span class="eyebrow">${type==='affidavit'?'AFFIDAVIT / DECLARATION':'MEESEVA APPLICATION'}</span><h2>${esc(title)}</h2><p>Complete the form on the left. Keep the listed documents ready before proceeding.</p></div><button class="small-btn" id="backForm">← Back</button></div><div class="form-workspace"><div class="iframe-wrap"><iframe id="serviceFrame" src="${url}" title="${esc(title)}"></iframe></div><aside class="requirements"><div class="requirements-head"><div class="req-icon">✓</div><div><h3>Documents to Keep Ready</h3><span>Guidance for this service</span></div></div><ul>${(checklistItems.length?checklistItems:['Original supporting records relevant to this service','Identity proof','Address proof','Authority-specific form or annexure, if prescribed']).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="fee-card"><span>Service fee</span><strong>₹${fee}</strong><small>Deducted from Wallet only when PDF is generated.</small></div><div class="req-note"><b>Important</b><br>Requirements can vary by the receiving authority. Carry originals and copies where applicable and verify the current requirements before signing or submitting.</div></aside></div></section>`;document.getElementById('backForm').addEventListener('click',()=>navigate(type==='affidavit'?'affidavits':'services'));prepareEmbeddedFrame(document.getElementById('serviceFrame'),type);}
function prepareEmbeddedFrame(frame,type){frame.addEventListener('load',()=>{try{const doc=frame.contentDocument;if(!doc)return;const s=doc.createElement('style');s.textContent=`html,body{width:100%!important;min-width:0!important;background:#f5f8fc!important;margin:0!important;padding:0!important}body{overflow-x:hidden!important}.portal-header,.portal-footer,.portal-nav,.portal-header-inner,.portal-main>header,body>header,body>footer,.portal-back,.back{display:none!important}.portal-page{padding:0!important;margin:0!important}.container{width:100%!important;max-width:none!important;margin:0!important;padding:22px 24px 42px!important;background:transparent!important;box-shadow:none!important;border-radius:0!important}.container>.card,.container .card{width:100%!important;max-width:none!important;margin:0!important}form{width:100%!important;max-width:none!important}.grid,.form-grid{width:100%!important}input,select,textarea{max-width:none!important}h1{margin-top:0!important}${type==='affidavit'?'.side,#checklist{display:none!important}':''}@media(max-width:760px){.container{padding:16px 12px 30px!important}.grid,.form-grid{grid-template-columns:1fr!important}}`;doc.head.appendChild(s);doc.documentElement.classList.add('kspl-embedded');}catch(e){console.warn(e);}});}
function wallet(){content.innerHTML=`<section class="panel"><div class="panel-head"><div><span class="eyebrow">SECURE WALLET</span><h2>Wallet</h2><p>Add money through Cashfree and use the balance for citizen service fees.</p></div></div><div class="wallet-hero"><div><span>Available Balance</span><strong id="walletBal">₹0.00</strong></div><div class="wallet-badge">Cashfree Secure Checkout</div></div><div class="topup-box"><div class="field"><label>Top-up Amount</label><input id="topupAmount" type="number" min="10" max="100000" step="1" placeholder="Minimum ₹10"></div><div class="amounts"><button type="button" data-amt="100">₹100</button><button type="button" data-amt="250">₹250</button><button type="button" data-amt="500">₹500</button><button type="button" data-amt="1000">₹1,000</button></div><button class="primary" id="topup">Add Money to Wallet</button><div id="walletMsg" class="msg hidden"></div></div></section><section class="panel"><div class="panel-head"><h2>Wallet Transactions</h2></div><div id="walletTx"></div></section>`;document.querySelectorAll('[data-amt]').forEach(b=>b.addEventListener('click',()=>topupAmount.value=b.dataset.amt));topup.addEventListener('click',doTopup);loadWallet();}
async function loadWallet(){try{const j=await api('/api/wallet');walletBal.textContent='₹'+j.balance.toFixed(2);walletTx.innerHTML=table(j.transactions);}catch(e){toast(e.message,true)}}
async function doTopup(){showMsg('walletMsg','Creating secure Cashfree payment…','info');try{const j=await api('/api/wallet/topup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount:Number(topupAmount.value)})});const cf=window.Cashfree({mode:j.environment==='production'?'production':'sandbox'});await cf.checkout({paymentSessionId:j.paymentSessionId,redirectTarget:'_self'});}catch(e){showMsg('walletMsg',e.message,'err')}}
function table(rows){if(!rows?.length)return'<div class="empty-state">No transactions yet.</div>';return`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Description</th><th>Amount</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString()}</td><td>${esc(x.description||'')}</td><td class="${x.direction==='credit'?'credit':'debit'}">${x.direction==='credit'?'+':'-'}₹${Number(x.amount).toFixed(2)}</td><td>${esc(x.status||'')}</td></tr>`).join('')}</tbody></table></div>`}
function transactions(){content.innerHTML=`<section class="panel"><div class="panel-head"><div><span class="eyebrow">HISTORY</span><h2>Transactions</h2><p>Search service fees, wallet top-ups and refunds by date.</p></div></div><div class="date-search"><div class="field"><label>From date</label><input id="from" type="date"></div><div class="field"><label>To date</label><input id="to" type="date"></div><button class="small-btn" id="searchTx">Search</button></div><div id="tx" class="transaction-result"></div></section>`;searchTx.addEventListener('click',loadTx);loadTx();}
async function loadTx(){try{const j=await api('/api/portal/transactions?from='+encodeURIComponent(from.value||'')+'&to='+encodeURIComponent(to.value||''));tx.innerHTML=table(j.transactions);}catch(e){toast(e.message,true)}}
function complaint(){content.innerHTML=`<section class="panel"><div class="panel-head"><div><span class="eyebrow">CITIZEN SUPPORT</span><h2>Raise a Complaint</h2><p>Submit your issue to Admin. The SR number is assigned after Admin resolves the complaint.</p></div></div><form id="complaintForm"><div class="form-grid"><div class="field full"><label>Subject</label><input id="subject" required></div><div class="field full"><label>Complaint / Query</label><textarea id="complaintText" required placeholder="Describe your issue or query"></textarea></div></div><button class="primary compact-btn" type="submit">Submit Complaint</button></form><div id="cmpMsg" class="msg hidden"></div></section><section class="panel"><div class="panel-head"><h2>My Complaints</h2></div><div id="myComplaints"></div></section>`;complaintForm.addEventListener('submit',async e=>{e.preventDefault();try{const j=await api('/api/portal/complaints',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject:subject.value,message:complaintText.value})});showMsg('cmpMsg',j.message,'ok');complaintForm.reset();await loadMyComplaints();}catch(err){showMsg('cmpMsg',err.message,'err')}});loadMyComplaints()}
async function loadMyComplaints(){try{const j=await api('/api/portal/complaints');myComplaints.innerHTML=j.complaints.length?j.complaints.map(c=>`<article class="citizen-complaint"><div><b>${esc(c.subject||'Complaint')}</b><span class="status-pill ${c.status==='RESOLVED'?'resolved':'open'}">${esc(c.status)}</span></div><p>${esc(c.message)}</p><small>${new Date(c.createdAt).toLocaleString()}${c.status==='RESOLVED'&&c.sr?` · SR Number: <b>${esc(c.sr)}</b>`:''}</small>${c.resolution?`<div class="resolution-box"><b>Admin Resolution</b><div>${esc(c.resolution)}</div></div>`:''}</article>`).join(''):'<div class="empty-state">No complaints yet.</div>'}catch(e){myComplaints.innerHTML='<div class="empty-state">Unable to load complaints.</div>'}}
function profile(){content.innerHTML=`<section class="panel profile-panel"><div class="panel-head"><div><span class="eyebrow">MY ACCOUNT</span><h2>Profile</h2><p>Your registered citizen details.</p></div></div><div class="profile-grid"><div class="profile-item"><span>Registered Name</span><strong>${esc(state.user.name)}</strong></div><div class="profile-item"><span>User ID</span><strong>${esc(state.user.userId)}</strong></div><div class="profile-item"><span>Email ID</span><strong>${esc(state.user.email)}</strong></div><div class="profile-item"><span>Mobile Number</span><strong>${esc(state.user.mobile)}</strong></div><div class="profile-item"><span>City</span><strong>${esc(state.user.city)}</strong></div></div></section>`}
function password(){content.innerHTML=`<section class="panel narrow-panel"><div class="panel-head"><div><span class="eyebrow">SECURITY</span><h2>Change Password</h2><p>Choose a strong password you do not use elsewhere.</p></div></div><form id="pwForm"><div class="field"><label>Current Password</label><input id="cur" type="password" required></div><div class="field"><label>New Password</label><input id="newp" type="password" minlength="8" required></div><div class="field"><label>Confirm New Password</label><input id="conf" type="password" minlength="8" required></div><button class="primary compact-btn" type="submit">Change Password</button></form><div id="pwMsg" class="msg hidden"></div></section>`;pwForm.addEventListener('submit',async e=>{e.preventDefault();try{const j=await api('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:cur.value,newPassword:newp.value,confirmPassword:conf.value})});showMsg('pwMsg',j.message,'ok');setTimeout(auth,1800);}catch(err){showMsg('pwMsg',err.message,'err')}})}
async function logout(){try{await api('/api/auth/logout',{method:'POST'});}finally{localStorage.removeItem('kspl_auth_token');state.user=null;auth();}}
function pvc(){content.innerHTML=`<section class="panel"><div class="empty-module"><div class="empty-icon">◈</div><h2>Print PVC</h2><p>PVC printing is reserved for the next module. The menu and portal workspace are ready; the PVC workflow will be connected when the service requirements are provided.</p></div></section>`}
function toggleChat(){const root=document.getElementById('chatRoot');if(root.innerHTML){root.innerHTML='';return;}root.innerHTML=`<section class="chat"><div class="chat-head"><div><strong>Koutilya Support</strong><small>Automated citizen assistance</small></div><button id="chatClose">×</button></div><div class="chat-body" id="chatBody"><div class="bubble bot">Hello! I can help with login, MeeSeva applications, affidavits, wallet, transactions and complaints.</div></div><div class="chat-input"><input id="chatInput" placeholder="Type your message…"><button id="chatSend">Send</button></div></section>`;chatClose.addEventListener('click',toggleChat);chatSend.addEventListener('click',sendChat);chatInput.addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()});loadChatHistory();}
async function loadChatHistory(){try{const j=await api('/api/portal/chat');if(!j.chats?.length)return;chatBody.innerHTML='';j.chats.forEach(c=>{chatBody.insertAdjacentHTML('beforeend',`<div class="bubble me">${esc(c.message)}</div><div class="bubble bot">${esc(c.reply)}</div>`)});chatBody.scrollTop=chatBody.scrollHeight}catch(e){}}
async function sendChat(){const v=chatInput.value.trim();if(!v)return;chatBody.insertAdjacentHTML('beforeend',`<div class="bubble me">${esc(v)}</div>`);chatInput.value='';try{const j=await api('/api/portal/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:v})});chatBody.insertAdjacentHTML('beforeend',`<div class="bubble bot">${esc(j.reply)}</div>`);chatBody.scrollTop=chatBody.scrollHeight;}catch(e){chatBody.insertAdjacentHTML('beforeend',`<div class="bubble bot">${esc(e.message)}</div>`);}}
async function handleReturn(){const q=new URLSearchParams(location.search),oid=q.get('order_id');if(q.get('cashfree_return')==='1'&&oid){try{const j=await api('/api/wallet/verify/'+encodeURIComponent(oid));toast(j.paid?'Wallet top-up successful.':'Payment is not confirmed yet.',!j.paid);history.replaceState({},'',location.pathname);}catch(e){toast(e.message,true)}}}
function toast(text,error=false){const t=document.createElement('div');t.className='toast '+(error?'err':'ok');t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),3500);}
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.data?.type==='wallet-required'){toast(e.data.message||'Please add money to Wallet.',true);navigate('wallet');}});
(async()=>{try{const j=await api('/api/auth/me');state.user=j.user;if(j.user.mustChangePassword){forceChange();return;}await boot();}catch{auth();}})();
